### ISSUE TITLE
Curl in Service

### ISSUE THREAD

**Issue by salvadorcastro** [psfs/core#14]
It would be interesting to have methods to get info (_curl_getinfo_) and errors (_curl_error_, _curl_errno_) from the curl connection.
On the other hand, it's a bit confusing **headers** property in Service because it's used for nothing; it seems to be here to configure headers like CURLOPT_HTTPHEADER but this has to be configured as an option.

**Comment by c15k0** [comment]
The service class will be changed because I have to refactor this huge class. Thanks for your comments. I'll add your requirements because are very important for fathering info from the request.

**Comment by c15k0** [comment]
I've been added a method named getCallInfo that returns the curl_getinfo method information.
