### ISSUE TITLE
Add locale argument to t() function

### ISSUE THREAD

**Issue by gabmarfer** [psfs/core#21]
Allow to send a locale to the translator function `t()`. In the **_CustomTranslateExtension_**, just check if the argument is not null before setting the locale to get the translation:
`self::$locale = I18nHelper::extractLocale(Security::getInstance()->getSessionKey(I18nHelper::PSFS_SESSION_LANGUAGE_KEY));`

**Comment by c15k0** [comment]
Hello @gabmarfer, try to use `I18Helper::setLocale('locale')` to define the language to use in the translations.

**Comment by gabmarfer** [comment]
It works passing null as second argument and true as third argument. Thanks for the feedback.
t('message', null, true).
