### ISSUE TITLE
PSFS doesn't work with PHP@7.4 

### ISSUE THREAD

**Issue by gabmarfer** [psfs/core#24]
**Describe the bug**
PSFS doesn't work with PHP@7.4. It fails with error:
PHP Fatal error:  Trait 'PSFS\base\types\traits\SingletonTrait' not found in .../vendor/psfs/core/src/base/Logger.php on line 30

Seems something related to the psr-4 section of composer.json of PSFS.

**To Reproduce**
1. Install PHP 7.4
2. Open any project.
3. Run local server.
4. Make an API request and see error.

**Expected behavior**
Local server runs without issues.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.1 M1

**Additional context**

**Comment by c15k0** [comment]
Solved and upgraded the requirements from php7.1 to php7.2
